name: Terraform CI/CD

on: workflow_dispatch

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: envs/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Get public IP of GitHub runner
        id: ip
        run: echo "ADMIN_CIDR=$(curl -s https://checkip.amazonaws.com)/32" >> $GITHUB_ENV

      - name: Terraform Plan
        run: |
          terraform plan \
            -out=tfplan.out \
            -var="aws_region=${{ env.AWS_REGION }}" \
            -var="aws_access_key=${{ env.AWS_ACCESS_KEY_ID }}" \
            -var="aws_secret_key=${{ env.AWS_SECRET_ACCESS_KEY }}" \
            -var="admin_cidr=${{ env.ADMIN_CIDR }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan.out
